#+TITLE: Killing Giants 杀死巨人——“David and Goliath”书评

[[http://www.nytimes.com/2013/10/13/books/review/malcolm-gladwells-david-and-goliath.html][Source link]]

   Malcolm Gladwell: "We have a definition in our heads of what an
   advantage is — and the definition isn’t right. And what happens as
   a result? It means that we make mistakes. It means that we misread
   battles between underdogs and giants. It means that we
   underestimate how much freedom there can be in what looks like a
   disadvantage." 

   Malcolm Gladwell 的书总能带来超乎读者认知的新论点，如在
   /Outliers/ 中认为在成功的要素中，天分远不如于勤奋、运气以及背景重要。
   而在 /David and Goliath/ 中则提出弱者未必比强者没有优势，而强者的优
   势可能未必是真正的优势。也就是弱者在竞争中完全有可能击败强
   者而胜出。Malcolm Gladwell 非常善于找到能恰好支持自己观点的例子，但未必
   令人信服。

* Words and Phrases 

  + underdog: /n./ a person or group of people with less power, money, etc. than the rest of society
  + to wit: used to make clearer or more particular something that you have already said
  + delve into: to try hard to find out more information about sth
  + wind up: to find yourself in an unexpected and usually unpleasant situation, especially as a result of what you do
  + divine: /adj./ connected with a god, or like a god
  + elude: /vt./ If something that you want eludes you, you do not succeed in achieving it
  + dyslexic: /adj./ having dyslexia
  + dyslexia: /n./ impaired ability to learn to read
  + the Blitz: /n./ the German air attacks on the UK in 1940-41
  + advantageous: /adj./ giving advantages or helping to make you more successful
  + thought-provoking: /adj./ making you think a lot about a subject
  + knee-jerk: /adj./ a quick reaction that does not allow you time to
    consider sth carefully
  + constrarian: /n./ a person who takes a contrary position or attitude
  + counterintuitive: /adj./ opposite to what seems obvious or natural
  + slingshot: /n./ catapult
  + catapult: /n./ a device which can throw objects at a high speed
  + purport to: /vt./ to pretend to be or to do something, especially in a way that is not easy to believe
  + anecdotal: /adj./ describes information that is not based on facts or careful study
  + eminent: /adj./ famous, respected or import
  + leukemia: /n./ a serious disease in which the body produces too
    many white blood cells
  + presume: /vt./ to believe something to be true because it is very
    likely, although you are not certain
  + alight on: find by chance
  + go about: to begin to do something
  + psychiatrist: a doctor who treats people suffering from mental illness
  + employ: /vt./ to use sth
  + bewildering: /adj./  confusing and difficult to understand
  + sprawl: /n./ an act of spreading to cover a large area in an untidy way
  + shtick: /n./ (also schtick) a particular ability that sb has 